name: Crypto Bot Monthly Report

on:
schedule:
  - cron: '0 0 1 * *'  # يوم 1 من كل شهر في منتصف الليل UTC
workflow_dispatch:  # هذا السطر مهم للتشغيل اليدوي!

jobs:
send-crypto-report:
  runs-on: ubuntu-latest
  
  steps:
  - name: Checkout repository
    uses: actions/checkout@v4
    
  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.11'
      
  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install requests
      
  - name: Run crypto bot
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    run: python main.py
